### ISSUE TITLE
Project 264983948 doesn't load

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-svg-renderer#61]
https://scratch.mit.edu/projects/264983948/
https://llk.github.io/scratch-gui/develop/#264983948

I saw Oops in 3.0, with vm error `Document does not appear to be SVG.`

**Comment by apple502j** [comment]
Same for
https://scratch.mit.edu/projects/257681107/
https://scratch.mit.edu/projects/249004706/
https://scratch.mit.edu/projects/242801850/

**Comment by apple502j** [comment]
and even https://scratch.mit.edu/projects/238418048/

**Comment by apple502j** [comment]
yokobond on Twitter said that ungrouping the SVG fixes this. I tried that and it's working!
Maybe a good clue.
https://twitter.com/yokobond/status/1071926418517352448

**Comment by paulkaplan** [comment]
This is a problem we've seen before, some (apparently common) svg export mode from Illustrator includes undeclared entities in the SVG (things like `&ns_extends;`, `&ns_ai;`) that crash the DOMParser. We can provide those entity declarations manually, or find and replace the entities with their real link values. It is super annoying because all those entities do is reference namespace strings that don't do anything anyway...

**Comment by fsih** [comment]
@paulkaplan I guess you probably know already but that sounds like https://github.com/LLK/scratch-gui/issues/3534 and the text you can add to make the svg work is here: https://github.com/LLK/scratch-gui/issues/3534#issuecomment-442504760

**Comment by ktbee** [comment]
FYI as part of a fix for https://github.com/LLK/scratch-gui/issues/3534 and based on a Slack conversation with @thisandagain and @kchadha , I'm adding a backup solution for broken SVGs where we use the builtin `defaultVector.svg` asset in scratch-storage to replace broken SVGs instead of just throwing an error.
